name: Run VTX DEX Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'   # Har 5 minute mein restart (keep alive)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot requests pytz

      - name: Install Java (for ARM Killer)
        run: |
          sudo apt update
          sudo apt install openjdk-17-jre-headless -y

      - name: Run Bot
        run: |
          python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
