- name: Restore Database
  uses: actions/cache@v4
  with:
    path: vtxdex.db
    key: vtxdex-db-${{ github.run_id }}
    restore-keys: |
      vtxdex-db-

- name: Run Bot
  env:
    TELEGRAM_TOKEN: ${{ 8859660196:AAFnaqQAFo_DHZ3lEYRyNAEgG54IscXW8vg }}
    ADMIN_ID: ${{ 5510702228 }}
  run: |
    python bot.py

- name: Save Database
  if: always()
  uses: actions/cache@v4
  with:
    path: vtxdex.db
    key: vtxdex-db-${{ github.run_id }}
