name: VTX DEX Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: pip install python-telegram-bot==20.8 requests==2.31.0 pytz==2024.1
      
      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          FIREBASE_URL: "https://mn-rohan-default-rtdb.firebaseio.com"
        run: python bot.py
